### ISSUE TITLE
role の引数を <role_name>__args という dict で表現する

### ISSUE THREAD

**Issue by pollenjp** [pollenjp/ansible-lint-custom-strict-naming#14]
```yaml
- name: Include role
  ansible.builtin.include_role:
    name: samle
  vars:
    samle_role__args:
        var1: "VAR1"
        var2: "VAR2"
        var3: "VAR3"
```
